I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 392, in script
    if The_Superego>=3:
  File "game/script.rpy", line 392, in <module>
    if The_Superego>=3:
NameError: name 'The_Superego' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 392, in script
    if The_Superego>=3:
  File "/Applications/RenPy/renpy-8.3.7-sdk/renpy/ast.py", line 1856, in execute
    if renpy.python.py_eval(condition):
  File "/Applications/RenPy/renpy-8.3.7-sdk/renpy/python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Applications/RenPy/renpy-8.3.7-sdk/renpy/python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 392, in <module>
    if The_Superego>=3:
NameError: name 'The_Superego' is not defined

macOS-14.3.1-arm64-arm-64bit arm64
Ren'Py 8.3.7.25031702
Adventurer 1.0
Sun Jul 20 14:50:42 2025
